# Generated by Django 4.0.4 on 2022-05-12 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=20, null=True, verbose_name='위도')),
                ('lng', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=20, null=True, verbose_name='경도')),
            ],
            options={
                'verbose_name': '위치',
                'verbose_name_plural': '위치',
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='TargetPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50, verbose_name='지정된 장소명')),
                ('accept_range', models.PositiveIntegerField(default=100, verbose_name='GPS 허용 범위')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_places', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '지정된 장소',
                'verbose_name_plural': '지정된 장소',
                'db_table': 'target_place',
            },
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target_place', to='location.location', verbose_name='위치')),
                ('target_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.targetplace', verbose_name='지정된 장소')),
            ],
            options={
                'verbose_name': '위치 기록',
                'verbose_name_plural': '위치 기록',
                'db_table': 'location_history',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='주소')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='우편번호')),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location', verbose_name='위치')),
            ],
            options={
                'verbose_name': '주소',
                'verbose_name_plural': '주소',
                'db_table': 'address',
            },
        ),
    ]
