# Generated by Django 4.0.4 on 2022-05-12 01:16

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='상수 키')),
                ('value', models.TextField(blank=True, verbose_name='상수 값')),
            ],
            options={
                'verbose_name': '프로젝트 상수',
                'verbose_name_plural': '프로젝트 상수',
                'db_table': 'project_constant',
            },
        ),
    ]
