# Generated by Django 4.0.4 on 2022-05-12 01:36

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('target', models.CharField(blank=True, max_length=50, null=True, verbose_name='대상')),
                ('message', encrypted_fields.fields.EncryptedTextField(blank=True, null=True, verbose_name='내용')),
                ('subject', encrypted_fields.fields.EncryptedCharField(max_length=50, verbose_name='제목')),
            ],
            options={
                'verbose_name': '이메일 관리',
                'verbose_name_plural': '이메일 관리',
                'db_table': 'notification_email',
            },
        ),
        migrations.CreateModel(
            name='NotificationKaKaO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('target', models.CharField(blank=True, max_length=50, null=True, verbose_name='대상')),
                ('message', encrypted_fields.fields.EncryptedTextField(blank=True, null=True, verbose_name='내용')),
                ('status_code', models.CharField(max_length=10, verbose_name='상태 코드')),
                ('raw', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='오류 메세지')),
            ],
            options={
                'verbose_name': '카카오톡 관리',
                'verbose_name_plural': '카카오톡 관리',
                'db_table': 'notification_kakao',
            },
        ),
        migrations.CreateModel(
            name='NotificationSlack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('target', models.CharField(blank=True, max_length=50, null=True, verbose_name='대상')),
                ('message', encrypted_fields.fields.EncryptedTextField(blank=True, null=True, verbose_name='내용')),
                ('status_code', models.CharField(max_length=10, verbose_name='상태 코드')),
                ('raw', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='오류 메세지')),
                ('channel', models.CharField(max_length=50, verbose_name='채널')),
            ],
            options={
                'verbose_name': '슬랙 관리',
                'verbose_name_plural': '슬랙 관리',
                'db_table': 'notification_slack',
            },
        ),
        migrations.CreateModel(
            name='NotificationSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('target', models.CharField(blank=True, max_length=50, null=True, verbose_name='대상')),
                ('message', encrypted_fields.fields.EncryptedTextField(blank=True, null=True, verbose_name='내용')),
                ('status_code', models.CharField(max_length=10, verbose_name='상태 코드')),
                ('raw', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='오류 메세지')),
            ],
            options={
                'verbose_name': '문자 관리',
                'verbose_name_plural': '문자 관리',
                'db_table': 'notification_sms',
            },
        ),
        migrations.CreateModel(
            name='NotificationTwilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('target', models.CharField(blank=True, max_length=50, null=True, verbose_name='대상')),
                ('message', encrypted_fields.fields.EncryptedTextField(blank=True, null=True, verbose_name='내용')),
                ('status_code', models.CharField(max_length=10, verbose_name='상태 코드')),
                ('raw', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='오류 메세지')),
            ],
            options={
                'verbose_name': 'Twilio 관리',
                'verbose_name_plural': 'Twilio 관리',
                'db_table': 'notification_twilio',
            },
        ),
    ]
