FROM        python:3.9

# 라이브러리 설치
RUN         apt-get update -y
COPY        ./requirements/requirements.worker.txt /app/requirements.txt
RUN         pip install -U pip
RUN         pip install -r /app/requirements.txt

# 프로젝트 폴더로 이동
WORKDIR     /app

# 프로젝트 실행
CMD         celery -A conf worker -l info -Ofair

EXPOSE      80
