# Generated by Django 4.0.4 on 2022-05-12 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotContentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', encrypted_fields.fields.EncryptedTextField(null=True, verbose_name='내용')),
            ],
            options={
                'verbose_name': '챗봇 컨텐츠 - 텍스트',
                'verbose_name_plural': '챗봇 컨텐츠 - 텍스트',
                'db_table': 'chatbot_content_text',
            },
        ),
        migrations.CreateModel(
            name='ChatbotFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(max_length=100, verbose_name='사용자 키')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '챗봇 친구',
                'verbose_name_plural': '챗봇 친구',
                'db_table': 'chatbot_friend',
            },
        ),
        migrations.CreateModel(
            name='ChatbotContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='컨텐츠 연결')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatbotfriend', verbose_name='챗봇 친구')),
            ],
            options={
                'verbose_name': '챗봇 컨텐츠',
                'verbose_name_plural': '챗봇 컨텐츠',
                'db_table': 'chatbot_content',
            },
        ),
    ]
