version: "3.9"

networks:
  jay-net:
    name: jay-net
    ipam:
      config:
        - subnet: 172.20.1.0/24

services:
  api:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.api
    container_name: api
    hostname: api
    restart: always
    expose:
      - 80
    volumes:
      - ..:/app
    working_dir: /app/
    env_file: env/prod/.env.api
    networks:
      jay-net:
        ipv4_address: 172.20.1.2

  worker:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.worker
    container_name: worker
    hostname: worker
    restart: always
    volumes:
      - ..:/app
    depends_on:
      - api
    working_dir: /app/
    env_file: env/prod/.env.celery
    networks:
      jay-net:
        ipv4_address: 172.20.1.3

  proxy:
    image: nginxproxy/nginx-proxy
    container_name: proxy
    hostname: proxy
    restart: always
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - ../.static_root:/app/.static_root
#      - certs:/etc/nginx/certs
      - ./nginx_conf:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      jay-net:
        ipv4_address: 172.20.1.4

#  letsencrypt:
#    image: nginxproxy/acme-companion
#    container_name: letsencrypt
#    hostname: letsencrypt
#    restart: always
#    volumes_from:
#      - proxy
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - acme:/etc/acme.sh
#    env_file: env/prod/.env.nginx
#    networks:
#      jay-net:
#        ipv4_address: 172.20.1.5

  cache:
    image: rabbitmq
    container_name: cache
    hostname: cache
    restart: always
    expose:
      - 5672
    env_file: env/prod/.env.cache
    networks:
      jay-net:
        ipv4_address: 172.20.1.6

volumes:
  certs:
  html:
  acme:
