# Generated by Django 4.0.4 on 2022-05-12 01:16

import core.keys
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityRSAKeySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_public_key', encrypted_fields.fields.EncryptedTextField(verbose_name='공개 키')),
                ('public_key', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_public_key', hash_key=settings.ENCRYPTION_KEY, max_length=66, null=True, verbose_name='공개 키')),
                ('private_key', encrypted_fields.fields.EncryptedTextField(verbose_name='비밀 키')),
                ('expire_at', models.DateTimeField(help_text='공개키 생성 후 120초 까지만 유효', verbose_name='만료 시간')),
            ],
            options={
                'verbose_name': '보안 RSA 키셋',
                'verbose_name_plural': '보안 RSA 키셋',
                'db_table': 'security_rsa_key_set',
            },
        ),
        migrations.CreateModel(
            name='SecurityAESKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=core.keys.generate_random_string, max_length=32, verbose_name='AES 암호화 키')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '보안 AES 키',
                'verbose_name_plural': '보안 AES 키',
                'db_table': 'security_aes_key',
            },
        ),
    ]
