# Generated by Django 4.0.4 on 2022-05-12 01:16

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields
from django.contrib.auth.hashers import make_password


def initial_admin_user(apps, schema_editor):
    User = apps.get_model('user', 'User')
    UserProfile = apps.get_model('user', 'UserProfile')
    user = User.objects.create(
        email=settings.DEFAULT_ADMIN_EMAIL,
        password=make_password(settings.DEFAULT_ADMIN_PASSWORD),
        is_admin=True
    )
    UserProfile.objects.create(
        user=user,
        name=settings.DEFAULT_ADMIN_NAME
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='이메일 주소')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=20, null=True, verbose_name='이름')),
                ('name', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_name', hash_key=settings.ENCRYPTION_KEY, max_length=66, null=True, verbose_name='이름')),
                ('_phone', core.fields.PhoneNumberEncryptedField(blank=True, max_length=20, null=True, verbose_name='전화번호')),
                ('phone', core.fields.PhoneNumberSearchField(blank=True, db_index=True, encrypted_field_name='_phone', hash_key=settings.ENCRYPTION_KEY, max_length=66, null=True, verbose_name='전화번호')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 정보',
                'verbose_name_plural': '사용자 정보',
                'db_table': 'user_profile',
            },
        ),
        migrations.RunPython(initial_admin_user)
    ]
